### ISSUE TITLE
Missing name in your license file

### ISSUE THREAD

**Issue by wyhaines** [jgaskins/redis#10]
https://github.com/jgaskins/redis/blob/master/LICENSE#L3

You need to put your name in.

I wrote auto-instrumentation for your library for otel, and to test it, I just used your specs. I noticed the missing name when I was adding your license to the corresponding spec in my repo:  https://github.com/wyhaines/opentelemetry-instrumentation.cr/blob/main/spec/instrumentation/jgaskins_redis_spec.cr

I went ahead and dropped your name into my copy, but you probably want to get it inserted into your original, too.  :)

**Comment by jgaskins** [comment]
Oops! Fixed in https://github.com/jgaskins/redis/commit/10138fd6ad98d5751c882632b3fd15f5010fa189
