### ISSUE TITLE
Would you consider a rename for this shard?

### ISSUE THREAD

**Issue by jwoertink** [jgaskins/redis#13]
I know this is a SUPER big ask, so totally feel free to just say "nope" and close this :joy: 

Just a little context here:

https://discord.com/channels/591460182777790474/591597160492171264/998645278469009418

https://github.com/mosquito-cr/mosquito/pull/94#issuecomment-1187990999

https://github.com/cable-cr/cable/issues/46#issuecomment-1187963323

Basically because this shard uses the `Redis` namespace, and https://github.com/stefanwille/crystal-redis also uses the Redis namespace, these two shards can't be installed together in the same project. To make matters more difficult, this shard uses `module Redis`, and the other uses `class Redis`. Where this becomes an issue in the ecosystem is, for example, if a project wanted to use both Cable.cr and Mosquito, currently they both use the other redis shard so things are fine. If we wanted to move Cable to this shard, then Cable would conflict with Mosquito (or Sidekiq.cr for that matter..).

Now if you were to rename this shard, both shards could live in a project at the same time without conflict.

With that said, [Mosquito](https://github.com/mosquito-cr/mosquito/pull/96) is slowly working towards a way to abstract out the redis layer which may mean any sort of backend could be used. Though, that also may be quite some time.

**Comment by jgaskins** [comment]
Sorry for the late response, I only just happened to see all these issues. I'm not getting emails for any of them for some reason, despite watching the repo. But I do remember having [the discussion on Twitter](https://twitter.com/asterite/status/1549149077337686017).

The naming collision has definitely caused some problems and I don't *love* that, and when you consider that an application may not depend on either this shard or Stefan's directly, but instead downstream through other libraries, it can cause problems that an application can't even solve without some gnarly hacks. I actually tried at one point to build a compatibility layer with Stefan's shard and it mostly worked but was gross and didn't help things like instrumentation, which requires [monkeypatching types](https://github.com/wyhaines/opentelemetry-instrumentation.cr/blob/7d83b9a53c9540fbc159f06eeed5d4bdad5c4377/src/opentelemetry/instrumentation/shards/jgaskins_redis.cr#L10), not just providing `alias`es for APIs.

Naming this one `redis` seemed like a good idea at the time for discoverability. The Crystal ecosystem was much smaller but I think when people needed a Redis shard they saw that Stefan's shard had more stars or supported more Redis commands out of the box, and used that one.

I don't *want* to rename this shard, but I haven't found or heard any alternatives that are currently viable. Like you point out, some shards are working on making it possible to use different backends, but I don't think it's there yet and unfortunately it's causing problems *now*.

I'm open to ideas, though.
