### ISSUE TITLE
Allow customizing the log

### ISSUE THREAD

**Issue by jwoertink** [jgaskins/redis#29]
This log line doesn't do a setup for the shard (i.e. `Log.for("redis")` like it does here https://github.com/jgaskins/redis/blob/8502cf7533b4fb26d0141a8945ac11fd118e397f/src/cluster.cr#L35

We could add the configuration so then someone could configure this line to silence it or whatever.
https://github.com/jgaskins/redis/blob/8502cf7533b4fb26d0141a8945ac11fd118e397f/src/connection.cr#L252

**Comment by jgaskins** [comment]
Nice catch. I have a feeling I did that because I thought I added a `Log = ::Log.for(…)` like I did on `Cluster`. Either that or I didn’t mean to commit it. I can’t remember the context.

Either way, it should be consistent. :100:
