### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by jwoertink** [jgaskins/redis#33]
I'll preface this with saying I'm really bad about understanding this sort of thing....

On 9/27/22 I swapped [Mosquito](https://github.com/mosquito-cr/mosquito/pull/98) and [Cable](https://github.com/cable-cr/cable/pull/48) and deployed to production. The great news was we no longer had to do daily reboots due to redis disconnect issues, but on 10/2/22 our system came to a halt and required a full system reboot. We are using [InfluxDB](https://www.influxdata.com/) to monitor memory usage and stuff, and we saw this graph:

![image](https://user-images.githubusercontent.com/2391/193637697-6c2783bf-dc21-4259-9b34-8be35997bcd9.png)

The red line drop is 9/27 when we deployed, and the blue line line is the new Docker container that was spun up from 9/27 to 10/2 when we rebooted. Our live chat (through cable), and workers (through mosquito) all just stopped. Updating those 2 shards was the only change we had deployed leading me to believe maybe something in this shard could possibly be leaking memory? I'll keep investigating to see if I find any additional info.

**Comment by jwoertink** [comment]
That could be a possibility. I'm wondering if the memory leak has always existed, but swapping over to this shard just allowed us to handle it better? Or maybe something just got expose a bit more. Unfortunately I don't have any reference to go off to see if that's the case.

**Comment by jgaskins** [comment]
Just confirmed the problem isn't due to the port of `Mosquito::RedisBackend`. After running 1.5M jobs through it, it only uses 7.5MB.

<details><summary>Benchmark code</summary>

```crystal
require "../src/mosquito"

class BogusJob < Mosquito::QueuedJob
  params count : Int32

  def perform
    if rand
      log count
    end
  end
end

Mosquito.configure do |settings|
  settings.redis_url = ENV["REDIS_URL"]? || "redis://localhost:6379/3?max_idle_pool_size=60"
  settings.idle_wait = 10.milliseconds
end

Mosquito.configuration.backend.flush

Signal::INT.trap { Mosquito::Runner.stop }

50.times do
  spawn Mosquito::Runner.start
end

running = true
spawn do
  i = 0
  redis = Mosquito::RedisBackend.redis
  while running
    # Redis seems to struggle if we make the queue too large, so we cap it at 1k
    if redis.llen("mosquito:waiting:bogus_job").as(Int) < 1_000
      BogusJob.new(i += 1).enqueue
    else
      sleep 100.milliseconds
    end
  end
end

puts "Press Enter to exit"
gets
running = false
Mosquito::Runner.stop
```

Also found `LLEN` isn't auto-casted 🙃

</details>

I'll check `Cable` next.

**Comment by jgaskins** [comment]
Also, for that example code, I had to patch `Mosquito::Configuration#idle_wait` use a `Time::Span` to run that many jobs through it without waiting forever since the `to_unix` call returns integer seconds.

<details><summary>the patch</summary>

```patch
diff --git a/src/mosquito/configuration.cr b/src/mosquito/configuration.cr
index 1e8b253..c6165b8 100644
--- a/src/mosquito/configuration.cr
+++ b/src/mosquito/configuration.cr
@@ -7,7 +7,7 @@ module Mosquito
 
   class Configuration
     property redis_url : String?
-    property idle_wait : Float64 = 0.1
+    property idle_wait = 100.milliseconds
     property successful_job_ttl : Int32 = 1
     property failed_job_ttl : Int32 = 86400
 
@@ -18,7 +18,7 @@ module Mosquito
     property validated = false
 
     def idle_wait=(time_span : Time::Span)
-      @idle_wait = time_span.total_seconds
+      @idle_wait = time_span
     end
 
     def validate
diff --git a/src/mosquito/runner.cr b/src/mosquito/runner.cr
index 74b9091..58b82df 100644
--- a/src/mosquito/runner.cr
+++ b/src/mosquito/runner.cr
@@ -5,7 +5,7 @@ module Mosquito
     Log = ::Log.for self
 
     # Minimum time in seconds to wait between checking for jobs.
-    property idle_wait : Float64
+    property idle_wait : Time::Span
 
     # How long a job config is persisted after success
     property successful_job_ttl : Int32
@@ -22,9 +22,8 @@ module Mosquito
       Log.notice { "Mosquito is buzzing..." }
       instance = new
 
-      while true
+      while @@keep_running
         instance.run
-        break unless @@keep_running
       end
     end
 
@@ -41,7 +40,7 @@ module Mosquito
       @failed_job_ttl = Mosquito.configuration.failed_job_ttl
 
       @queues = [] of Queue
-      @start_time = 0_i64
+      @start_time = 0.seconds
       @execution_timestamps = {} of Symbol => Time
     end
 
@@ -55,11 +54,11 @@ module Mosquito
     end
 
     private def set_start_time
-      @start_time = Time.utc.to_unix
+      @start_time = Time.monotonic
     end
 
     private def idle
-      delta = Time.utc.to_unix - @start_time
+      delta = Time.monotonic - @start_time
       if delta < idle_wait
         sleep(idle_wait - delta)
       end
```

</details>

**Comment by jgaskins** [comment]
I can't replicate this in Cable, either. This example app with 6 tabs open (spamming the server 60x/sec per tab) uses 5.2MB of RAM on my machine:

<details><summary>Code</summary>

```crystal
require "../src/cable"
require "http"
require "ecr"

module ApplicationCable
  class Connection < Cable::Connection
    identified_by :identifier

    def connect
    end
  end

  class Channel < Cable::Channel
  end

  class ChatChannel < Channel
    getter identifier = "lol"

    def subscribed
      stream_from identifier
    end

    def receive(data)
      self.class.broadcast_to identifier, {
        "message" => data["message"].to_s,
        "user_id" => "the user",
      } of String => String
    end

    def perform(action, params)
      self.class.broadcast_to identifier, {
        "user"      => "me",
        "performed" => action.to_s,
      } of String => String
    end
  end
end

Cable.configure do |c|
  c.route = "/cable"
  c.token = "token"
  c.url = "redis:///1"
end

class App
  include HTTP::Handler

  def call(context)
    case {context.request.method, context.request.path}
    when {"GET", "/"}
      context.response << <<-HTML
        <!doctype html>
        <script type="module" src="https://unpkg.com/@rails/actioncable@7.0.4/app/assets/javascripts/actioncable.js"> </script>
        <script type="module">
          const consumer = ActionCable.createConsumer('/cable?token=omg')
          window.chat = consumer.subscriptions.create({channel: "ApplicationCable::ChatChannel"})
          function send() {
            chat.send({message: Math.random().toString()})
            requestAnimationFrame(send)
          }
          send()
        </script>
      HTML
    else
      context.response.status = :not_found
      context.response << "Not found"
    end
  end
end

http = HTTP::Server.new([
  HTTP::LogHandler.new,
  Cable::Handler(ApplicationCable::Connection).new,
  App.new,
])
port = ENV.fetch("PORT", "3000").to_i
Log.for("http.server").info { "Listening on #{port}" }
http.listen port
```

</details>

**Comment by jgaskins** [comment]
Wait, I *can* replicate a memory leak in Cable. It's not about messages being sent over the wire, though. It's about the WebSocket connections being made to the app — hold down Cmd-R on the page loaded via the code in my previous comment and watch memory consumption climb steadily and never come back down or even plateau.

But that also happens on Cable's `master` branch with the other Redis client, as well, so I'm not sure the leak is here. I don't know how to explain how you had more memory usage than you were seeing before, though, assuming you were getting roughly equal page views.

**Comment by jwoertink** [comment]
Wow! That's some great investigation. Yeah, we can close this out. I guess I need to really dive in to Cable to figure out where that leak is coming from. 

I also like that Mosquito patch. Maybe @robacarp might be interested in that? 

Thanks so much for finding this! :raised_hands:
