### ISSUE TITLE
Release milestone?

### ISSUE THREAD

**Issue by robacarp** [jgaskins/redis#36]
Hey, I'm looking at finishing up https://github.com/mosquito-cr/mosquito/pull/98 and was surprised to see there's a long series of commits between [master and the most recent release](https://github.com/jgaskins/redis/compare/v0.3.0...master).

I'd like to avoid pinning to a specific commit, if possible. Do you have a list of need-to-finish items before releasing a new version? I'd be happy to help check things off if so.

**Comment by jgaskins** [comment]
Ooh, thank you for reminding me. I thought I'd released a version with some of the recent changes. Must've gotten distracted along the way. I'll do that now.

**Comment by jgaskins** [comment]
Just released [`v0.6.0`](https://github.com/jgaskins/redis/releases/tag/v0.6.0). Thanks again for the reminder!

**Comment by jgaskins** [comment]
Oh, now I remember why I didn't release it before. I wanted to handle https://github.com/jgaskins/redis/issues/32 first. Lemme see what I can do with that this evening.

**Comment by robacarp** [comment]
Oh great, thank you! 🎂
