### ISSUE TITLE
The current tag has the wrong shard version

### ISSUE THREAD

**Issue by jwoertink** [jgaskins/redis#45]
This is in tag v0.7.0

https://github.com/jgaskins/redis/blob/df0614fd177dc35a559e96a81781e17ff07cfbf0/shard.yml#L2

**Comment by jgaskins** [comment]
Sorry, I meant to get back to this and got distracted. This happened because I tagged the wrong commit. 🙃 

<img width="605" alt="image" src="https://github.com/jgaskins/redis/assets/108205/d2c3283f-606b-4d03-bb56-28993f0c7900">

I released v0.7.1 just now with a few fixes.
